In [82]:
import numpy as np

1. (5 баллов) Найти ближайшую ортогональную матрицу (в смысле нормы Фробениуса) к матрице A. Посмотрев на результат, найти соответствующие этому преобразованию угол и направление поворота. Матрицу, угол и направление поворота распечатать в stdout.


In [83]:
def nearest_orthogonal_matrix(A):
    U, S, V = np.linalg.svd(A)
    B = U @ V
    return B


A = np.array([[0.5, 2.16506351, 0.4330127],
              [-0.8660254, 1.25, 0.25],
              [0., 0.5, 2.5]])
B = nearest_orthogonal_matrix(A)
print(f"Матрица A:\n{A}")
print(f"Ближайшая ортогональная матрица к A:\n{B}")

Матрица A:
[[ 0.5         2.16506351  0.4330127 ]
 [-0.8660254   1.25        0.25      ]
 [ 0.          0.5         2.5       ]]
Ближайшая ортогональная матрица к A:
[[ 5.00000000e-01  8.66025404e-01 -3.87999535e-10]
 [-8.66025404e-01  5.00000000e-01  1.65510277e-11]
 [ 2.08333332e-10  3.27742012e-10  1.00000000e+00]]


In [84]:
x = np.arctan(np.divide(B[2, 1], B[2, 2])) * (180 / np.pi)
y = np.arcsin(B[2, 0]) * (180 / np.pi)
z = np.arctan(np.divide(B[1, 0], B[0, 0])) * (180 / np.pi)
x, y, z

(1.8778234064568186e-08, 1.1936620632782995e-08, -59.999999975140156)

2. (5 баллов) При помощи SVD найти обратную матрицу к квадратной матрице nxn, состоящей из элементов:
   $$
   A_{i,j} = \frac{1}{i+j-1}
   $$
для размеров матрицы n=3 и n=10. Результат распечатать в stdout.

In [85]:
def create_matrix(n):
    A = np.zeros((n, n))
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            A[i - 1, j - 1] = 1 / (i + j - 1)
    return A

In [86]:
n = 3
A = create_matrix(n)

U, S, V = np.linalg.svd(A)

sigma_plus = np.zeros((n, n))
sigma_plus[: min(n, n), : min(n, n)] = np.diag(1 / S)

A_inv = V.T @ sigma_plus @ U.T

print(f"Матрица обратная к A: {A_inv}")

Матрица обратная к A: [[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]


In [87]:
n = 10
A = create_matrix(n)

U, S, V = np.linalg.svd(A)

sigma_plus = np.zeros((n, n))
sigma_plus[: min(n, n), : min(n, n)] = np.diag(1 / S)

A_inv = V.T @ sigma_plus @ U.T

print(f"Матрица обратная к A: {A_inv}")

Матрица обратная к A: [[ 9.99968801e+01 -4.94972983e+03  7.91942351e+04 -6.00547514e+05
   2.52226935e+06 -6.30561027e+06  9.60846741e+06 -8.75050471e+06
   4.37522463e+06 -9.23653401e+05]
 [-4.94973007e+03  3.26676635e+05 -5.88010158e+06  4.75629832e+07
  -2.08086238e+08  5.35075001e+08 -8.32333747e+08  7.70046179e+08
  -3.89834079e+08  8.31292651e+07]
 [ 7.91942458e+04 -5.88010206e+06  1.12896900e+08 -9.51253754e+08
   4.28061541e+09 -1.12365573e+10  1.77564570e+10 -1.66330265e+10
   8.50549697e+09 -1.82885159e+09]
 [-6.00547659e+05  4.75629917e+07 -9.51253842e+08  8.24415817e+09
  -3.78714437e+10  1.00990164e+11 -1.61583782e+11  1.52889644e+11
  -7.88335475e+10  1.70693388e+10]
 [ 2.52227025e+06 -2.08086297e+08  4.28061621e+09 -3.78714471e+10
   1.76732974e+11 -4.77178018e+11  7.71195403e+11 -7.35782223e+11
   3.82040250e+11 -8.32132532e+10]
 [-6.30561324e+06  5.35075205e+08 -1.12365604e+10  1.00990182e+11
  -4.77178058e+11  1.30139343e+12 -2.12078752e+12  2.03755261e+12
  -1.064256

3. (5 баллов) Для квадратной матрицы nxn, состоящей из элементов:
   $$
   A_{i,j} = i + j - 1
   $$
   найти с использованием SVD все решения уравнений AX = 0 для n=4. Результат распечатать в stdout.


In [88]:
n = 4
A = np.array([i + j - 1 for i in range(n) for j in range(n)]).reshape((n, n))
A

array([[-1,  0,  1,  2],
       [ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 2,  3,  4,  5]])

In [89]:
U, S, V = np.linalg.svd(A)
x = V.T[:, np.isclose(S, 0)]
x

array([[ 0.34691234, -0.42385354],
       [-0.14662801,  0.82371125],
       [-0.747481  , -0.37586188],
       [ 0.54719667, -0.02399583]])

In [90]:
for i, val in enumerate(x, 1):
    print(f"x{i} = {val[0]:.4f}*a1 + {val[1]:.4f}*a2")

x1 = 0.3469*a1 + -0.4239*a2
x2 = -0.1466*a1 + 0.8237*a2
x3 = -0.7475*a1 + -0.3759*a2
x4 = 0.5472*a1 + -0.0240*a2


4. (5 баллов) Написать программу, находящую все точки пересечения двух прямых на плоскости методом однородных координат. Прямые заданы уравнениями ax+by+c = 0, cx+dy+e=0. Коэффициенты задать константами на ваше усмотрение. Результат распечатать в stdout.


In [91]:
def find_intersection_point(a, b, c, d, e):
    line1 = np.array([a, b, c])
    line2 = np.array([c, d, e])
    intersection_point = np.cross(line1, line2).astype(float)
    intersection_point /= intersection_point[2]
    return intersection_point[:2]


a, b, c = 1, 2, 3
c, d, e = 4, 5, 6

intersection_point = find_intersection_point(a, b, c, d, e)
print("Точка пересечения прямых:", intersection_point)

Точка пересечения прямых: [ 2.66666667 -3.33333333]
